#!/bin/bash
#retrieve name and arguments
self[0]=`basename "$0"`;
self[1]=$1;
self[2]=$2;
self[3]=$3;
self[4]=$4;
self[5]=$5;
for i in ${self[@]}; do echo $i; done

var1=$1
var2=$2
var3=$3
var4=$4
var5=$5
    if [ [ -z $var1 ] || [ -z $var2 ] || [ -z $var3 ] || [ -z $var4 ] || [ -z $var5 ] ]
    then
            if [ [!-z $var1] ]
            then
            echo argument ${var1} exists
            else
            echo argument ${var1} does not exist
            fi
            if [ [!-z $var2] ]
            then
            echo argument ${var2} exists
            else
            echo argument ${var2} does not exist
            fi
	    if [ [!-z $var3] ]
            then
            echo argument ${var3} exists
            else
            echo argument ${var3} does not exist
            fi
            if [ [!-z $var4] ]
            then
            echo argument ${var4} exists
            else
            echo argument ${var4} does not exist
            fi
            if [ [!-z $var5] ]
            then
            echo argument ${var5} exists
            else
            echo argument ${var5} does not exist
            fi
    else
    echo "Arguments are zero or > 5"
    exit 1
    fi

printf 'slength:%s\n' "$slength";
