#!/bin/bash
#base href = https://www.serverproject.de
#this is toodoo intro version < 1
#it is evaluation, examination, experiment and exercise
#the code is commented in english and german
#fragile || predictable

#retrieve name
var0=`basename "$0"`;
#output name
echo $var0;
#blob
URL=https://github.com/ewingson/edx-02-intro/blob/master/intro
#set tmp
tmp="temp"
#debug-mode
debug=false;

#argumentzuweisung
self[0]=$1;
self[1]=$2;
self[2]=$3;
self[3]=$4;
self[4]=$5;

#we must check if arguments are set
if [ -z "$1" ]
then
{ var1=null;
b1=false; }
else 
{ var1=$1;
b1=true; }
fi
if [ -z "$2" ]
then
{ var2=null;
b2=false; }
else 
{ var2=$2;
b2=true; }
fi
if [ -z "$3" ]
then
{ var3=null;
b3=false; }
else 
{ var3=$3;
b3=true; }
fi
if [ -z "$4" ]
then
{ var4=null;
b4=false; }
else 
{ var4=$4;
b4=true; }
fi
if [ -z "$5" ]
then
{ var5=null;
b5=false; }
else 
{ var5=$5;
b5=true; }
fi
if [ -z "$6" ]
then
{ okay=true; }
else 
{ okay=false; }
fi

#COUNTER (not yet used)
#count[1]=$var1;
#count[2]=$var2;
#count[3]=$var3;
#count[4]=$var4;
#count[5]=$var5;

#deprecated alternative extreme array conscience programming (rule conform)

#output and count arguments
j=0
for i in ${self[@]}; do
echo $i
j+=1
done
slength="$j"
size=${#slength}
#echo $COUNTER

#now we have all we need

#check the five boolean
if [[ "$b1" = true && "$okay" = true ]]
then flag=true
else flag=false
fi
    if [ "$flag" = true ]
    then
#whether exists or not output status and argument 
            if [ "$b1" = true ]
            then
            echo argument ${var1} exists
#other case
            else
            echo argument ${var1} does not exist
            fi
            if [ "$b2" = true ]
            then
            echo argument ${var2} exists
            else
            echo argument ${var2} does not exist
            fi
	    if [ "$b3" = true ]
            then
            echo argument ${var3} exists
            else
            echo argument ${var3} does not exist
            fi
            if [ "$b4" = true ]
            then
            echo argument ${var4} exists
            else
            echo argument ${var4} does not exist
            fi
            if [ "$b5" = true ]
            then
            echo argument ${var5} exists
            else
            echo argument ${var5} does not exist     
            fi
    else
#error message and exit if invalid number of arguments
    echo "Arguments are zero or > 5"
#exit 1
    exit 1
    fi
#array syntax is variable[index]=$value
arrlength=$size-1;
echo $size;

#toodoo
#we want printf(%d total %d arguments, $size, $arrlength);

#toodoo
#direction = (0 || 1 || 2038 || x203x || 4 || (5 && true))

#SI-Einheiten

#SI seconds for light to sun
sun=8*60
#SI seconds for lifetime sun
runtime=5000000000*365*24*60*60
#SI speed of light in meter/second
lightspeed=299792458
#SI distance light makes in a year in meter/year
lightyear=9460730472580800
#SI hoehe geostationaere umlaufbahn in meter
geosthoehe=35786000
#SI gravity (earth acceleration) in meter/second^2
grav=9,81
#alphabet
alphabet="abcdefghijklmnopqrstuvwxyz"

#if (variable0=true)
#{
#ping6 2a01:488:42:1000:50ed:854a:cc:d5a8
#}

#check $debug
if ($debug)
then
#ping solidweb.org
{ ping 83.169.46.66; }
else
#output string 'normal'
{ echo normal; }
fi

#exit 0
exit 0
